name: 'Similar Package Reviewer'
description: 'Provides a summary of similar packages detected by analyzing pull requests for new dependencies, powered by ChatGPT'
author: 'hmu332233'
branding:
  icon: 'check-square'
  color: 'gray-dark'
inputs:
  openai_key:
    description: 'openai api key'
    required: true
  origin_branch:
    description: 'The branch to be used as the base for comparison, typically the main branch of the project. Can be customized if needed.'
    default: origin/${{ github.base_ref }}
  target_branch:
    description: 'The branch associated with the pull request, which contains the changes to be compared against the origin branch. Can be customized if needed.'
    default: origin/${{ github.head_ref }}
  use_functioncall:
    description: 'Indicates whether to use the functioncall feature of ChatGPT. Using functioncall can provide more stable execution but may produce slightly different comparison results.'
    default: false
  model:
    description: 'Specifies the ChatGPT model to be used for analyzing pull requests. Different models may provide varying levels of analysis accuracy and performance. Default is gpt-3.5-turbo.'
    default: gpt-3.5-turbo

outputs:
  results:
    description: 'A summary of any similar packages detected during the comparison, intended to be posted as a comment on the pull request for review and consideration.'

runs:
  using: 'node16'
  main: 'dist/index.js'
